[versions]
kotlin = "2.0.21"
ktor = "2.3.12"
vertx = "4.5.11"
openai-client = "3.8.2"
jlayer = "1.0.1"
jackson-databind = "2.18.1"
joor = "0.9.15"
commons-lang3 = "3.17.0"
commons-io = "2.17.0"
pebble = "3.2.2"
jtokkit = "1.1.0"
libfvad-jni = "1.0.0"
vertexai = "1.13.0"
mockito-kotlin = "5.4.0"
snakeyaml = "2.3"
jna = "5.15.0"
guava = "33.3.1-jre"
kotlin-logging-jvm = "7.0.0"
logback-classic = "1.5.12"

[libraries]
vertx-core = { module = "io.vertx:vertx-core", version.ref = "vertx" }
vertx-lang-kotlin-coroutines = { module = "io.vertx:vertx-lang-kotlin-coroutines", version.ref = "vertx" }
ktor-client-java-jvm = { module = "io.ktor:ktor-client-java-jvm", version.ref = "ktor" }
ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-serialization-kotlinx-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
snakeyaml = { module = "org.yaml:snakeyaml", version.ref = "snakeyaml" }
jna = { module = "net.java.dev.jna:jna", version.ref = "jna" }
guava = { module = "com.google.guava:guava", version.ref = "guava" }
kotlin-logging-jvm = { module = "io.github.oshai:kotlin-logging-jvm", version.ref = "kotlin-logging-jvm" }
logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "logback-classic" }
openai-client = { module = "com.aallam.openai:openai-client", version.ref = "openai-client" }
jlayer = { module = "javazoom:jlayer", version.ref = "jlayer" }
jackson-databind = { module = "com.fasterxml.jackson.core:jackson-databind", version.ref = "jackson-databind" }
joor = { module = "org.jooq:joor", version.ref = "joor" }
commons-lang3 = { module = "org.apache.commons:commons-lang3", version.ref = "commons-lang3" }
commons-io = { module = "commons-io:commons-io", version.ref = "commons-io" }
pebble = { module = "io.pebbletemplates:pebble", version.ref = "pebble" }
jtokkit = { module = "com.knuddels:jtokkit", version.ref = "jtokkit" }
libfvad-jni = { module = "io.github.givimad:libfvad-jni", version.ref = "libfvad-jni" }
vertexai = { module = "com.google.cloud:google-cloud-vertexai", version.ref = "vertexai" }
mockito-kotlin = { module = "org.mockito.kotlin:mockito-kotlin", version.ref = "mockito-kotlin" }

[plugins]
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
